---
name: App-ZofCMS-Plugin-Captcha
version: 0.0102
author:
  - "'Zoffix <'zoffix@cpan.org'>"
abstract: plugin to utilize security images (captchas)
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  App::ZofCMS::Plugin::Base: 0.0105
  GD::SecurityImage: 1.7
configure_requires:
  Module::Build: 0.34
provides:
  App::ZofCMS::Plugin::Captcha:
    file: lib/App/ZofCMS/Plugin/Captcha.pm
    version: 0.0102
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
